# Generated by Django 4.2 on 2023-04-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('tag', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='pictures')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('tel', models.CharField(max_length=200, null=True)),
                ('aboutHead', models.CharField(max_length=200, null=True)),
                ('causeHead', models.CharField(max_length=200, null=True)),
                ('whatHead', models.CharField(max_length=200, null=True)),
                ('donateHead', models.CharField(max_length=200, null=True)),
                ('donateContent', models.TextField(null=True)),
                ('teamHead', models.CharField(max_length=200, null=True)),
                ('testimonieHead', models.CharField(max_length=200, null=True)),
                ('contactHead', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('service', models.CharField(max_length=200, null=True)),
                ('overview', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('profession', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Trustee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('designation', models.CharField(max_length=200, null=True)),
                ('icon', models.ImageField(null=True, upload_to='pictures')),
            ],
        ),
        migrations.CreateModel(
            name='WhatWeDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(null=True)),
                ('icon', models.ImageField(null=True, upload_to='pictures')),
            ],
        ),
    ]
