# Generated by Django 4.2 on 2023-04-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(null=True)),
                ('image1', models.ImageField(null=True, upload_to='pictures')),
                ('image2', models.ImageField(null=True, upload_to='pictures')),
            ],
        ),
    ]
