# Generated by Django 4.2 on 2023-04-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinformation',
            name='contactContent',
            field=models.TextField(null=True),
        ),
    ]
