# Generated by Django 4.2 on 2023-04-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_generalinformation_contactcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecause',
            name='goal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='featurecause',
            name='raised',
            field=models.IntegerField(null=True),
        ),
    ]
