# Generated by Django 4.2 on 2023-04-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_featurecause_goal_featurecause_raised'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trustee',
            old_name='icon',
            new_name='image',
        ),
    ]
