# Generated by Django 4.2 on 2023-04-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_rename_icon_trustee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinformation',
            name='pageHeaderImage',
            field=models.ImageField(null=True, upload_to='pictures'),
        ),
    ]
