# Generated by Django 4.2 on 2023-04-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_generalinformation_pageheaderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinformation',
            name='logo',
            field=models.ImageField(null=True, upload_to='pictures'),
        ),
    ]
