# Generated by Django 4.2 on 2023-04-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_generalinformation_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinformation',
            name='logo2',
            field=models.ImageField(null=True, upload_to='pictures'),
        ),
    ]
