# Generated by Django 4.2 on 2023-04-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_generalinformation_logo2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='pictures')),
                ('caption', models.CharField(max_length=200, null=True)),
                ('tag', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
