# Generated by Django 5.2.4 on 2025-07-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_galleryvideo_paragraph_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryvideo',
            old_name='image',
            new_name='video',
        ),
    ]
