# Generated by Django 5.2.4 on 2026-08-24 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_rename_image_galleryvideo_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('note', models.CharField(help_text="e.g. 'Primary beneficiaries'.", max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('concept', models.CharField(blank=True, help_text="e.g. 'Raḥmah' — leave blank if none.", max_length=100, null=True)),
                ('description', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Core Values',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DayTimelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_label', models.CharField(help_text="e.g. 'Arrival'.", max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DonationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('goal', models.PositiveIntegerField(blank=True, help_text='Leave blank until a real fundraising goal is set.', null=True)),
                ('raised', models.PositiveIntegerField(blank=True, help_text='Leave blank until real figures are available.', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('event_date', models.DateField(blank=True, help_text='Leave blank if not yet scheduled.', null=True)),
                ('date_label', models.CharField(blank=True, help_text="Shown instead of event_date if that's blank, e.g. 'Date to be announced'.", max_length=150, null=True)),
                ('is_sample', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Event Categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FounderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Prof. Mansir Dodo', max_length=200)),
                ('role_title', models.CharField(default='Founder & Visionary', max_length=200)),
                ('bio', models.TextField(help_text="The founder's welcome / profile message.")),
                ('quote', models.CharField(blank=True, help_text="Optional short signature line, e.g. '— Prof. Mansir Dodo, Founder'.", max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pictures')),
            ],
            options={
                'verbose_name': 'Founder Profile',
                'verbose_name_plural': 'Founder Profile',
            },
        ),
        migrations.CreateModel(
            name='FutureCentreZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FuturePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. 'Phase 01'.", max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional short description shown alongside this category.', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InquiryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Partner Categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text="Short display tag, e.g. '01'.", max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('short', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('book', 'Book (Education)'), ('shield', 'Shield (Welfare/Protection)'), ('spark', 'Spark (Empowerment)'), ('hands', 'Hands (Community)'), ('bowl', 'Bowl (Feeding)'), ('tool', 'Tool (Skills)')], default='book', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Representative photo for this pillar on the Programs page.', null=True, upload_to='pictures')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('outcome', models.CharField(help_text='Intended outcome, one sentence.', max_length=300)),
                ('icon', models.CharField(choices=[('book', 'Book (Education)'), ('shield', 'Shield (Welfare/Protection)'), ('spark', 'Spark (Empowerment)'), ('hands', 'Hands (Community)'), ('bowl', 'Bowl (Feeding)'), ('tool', 'Tool (Skills)')], default='book', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Roadmap Activities',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text="e.g. 'Short Term'.", max_length=100)),
                ('focus', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('excerpt', models.TextField()),
                ('body', models.TextField(blank=True, help_text='Optional full article body.', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('date_label', models.CharField(blank=True, help_text="e.g. a real date, or 'Sample story — placeholder'.", max_length=100, null=True)),
                ('is_sample', models.BooleanField(default=False, help_text='Marks this as illustrative placeholder content on the front end.')),
                ('is_featured', models.BooleanField(default=False, help_text='Show as the large featured story at the top of the Stories page.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Story Categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Team / Board Member',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
                ('quote', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='FeatureCause',
        ),
        migrations.DeleteModel(
            name='Outlet',
        ),
        migrations.DeleteModel(
            name='Paragraph',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.DeleteModel(
            name='Testimonie',
        ),
        migrations.DeleteModel(
            name='Trustee',
        ),
        migrations.DeleteModel(
            name='WhatWeDo',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About Section', 'verbose_name_plural': 'About Section'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['order', '-id'], 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='galleryvideo',
            options={'ordering': ['order', '-id']},
        ),
        migrations.AlterModelOptions(
            name='generalinformation',
            options={'verbose_name': 'General Information', 'verbose_name_plural': 'General Information'},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='galleryvideo',
            name='tag',
        ),
        migrations.AddField(
            model_name='gallery',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gallery',
            name='size_hint',
            field=models.CharField(choices=[('wide', 'Wide'), ('tall', 'Tall'), ('square', 'Square')], default='square', help_text='Controls masonry layout sizing on the front end.', max_length=10),
        ),
        migrations.AddField(
            model_name='galleryvideo',
            name='caption',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='galleryvideo',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='founder_name',
            field=models.CharField(default='Prof. Mansir Dodo', max_length=200),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='future_centre_concept_image',
            field=models.ImageField(blank=True, help_text='Whole-site conceptual render for the top of the Future Centre page.', null=True, upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='future_centre_intro',
            field=models.TextField(blank=True, help_text='Intro paragraph for the Future Centre page/section.', null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='hero_badge_label',
            field=models.CharField(blank=True, default='Strategic Focus Areas', help_text='Label shown under the hero badge number.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='hero_badge_number',
            field=models.CharField(blank=True, default='4', help_text='Number shown in the floating hero badge.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='hero_image_float',
            field=models.ImageField(blank=True, help_text='Small floating photo overlapping the main hero photo.', null=True, upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='hero_image_main',
            field=models.ImageField(blank=True, help_text='Large hero photo on the homepage.', null=True, upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='org_name',
            field=models.CharField(default='Alhazawa Orphans & Girl Child Foundation', max_length=200),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='caption',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='aboutHead',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='causeHead',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='contactContent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='contactHead',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='donateContent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='donateHead',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='logo2',
            field=models.ImageField(blank=True, help_text='Secondary/footer logo variant (optional).', null=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='pageHeaderImage',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='teamHead',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='testimonieHead',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='whatHead',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='src.eventcategory'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='src.gallerycategory'),
        ),
        migrations.AddField(
            model_name='galleryvideo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='src.gallerycategory'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='inquiry_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.inquirytype'),
        ),
        migrations.AddField(
            model_name='roadmapactivity',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='src.roadmapstage'),
        ),
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='src.storycategory'),
        ),
    ]
