# Generated by Django 5.2.4 on 2026-08-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_beneficiary_contactmessage_corevalue_daytimelinestep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinformation',
            name='problem_section_image',
            field=models.ImageField(blank=True, help_text='Photo or map shown next to "The Challenge" section on the homepage (Malumfashi/Katsina panel). Leave blank to use the default abstract graphic.', null=True, upload_to='pictures'),
        ),
    ]
