# Generated by Django 5.2.4 on 2026-08-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_generalinformation_problem_section_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinformation',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
